### ISSUE TITLE
omit, flatten, compact?

### ISSUE THREAD

**Issue by karansag** [pytoolz/toolz#176]
I've been using my own functions to do these. Is there any demand for them? Or any reason they're not included?
Mirroring the implementations in:
http://underscorejs.org/

**Comment by groutr** [comment]
I'm +1 on a recursive flatten.  I have found the ability to flatten and unflatten a dictionary incredibly useful on a handful of occasions, particularly when transforming deeply nested json.

**Comment by AlJohri** [comment]
I'm also a +1 on recursive flatten. I just found myself with the following data `[['top_section'], 'newsletter', ['uid', 'oid', 'gen_date']]` and was hoping a function in toolz could just handle flattening it.

**Comment by simonnier** [comment]
I vote for adding flatten. This post opened 2014. But `flatten` is still not included in `toolz` in 2020! Why not? I do not understand.  As `toolz` doc mentioned `underscore` as a typical FP package, I have just checked that there is `flatten` in `underscore`! And there is much powerful `Flatten` in Mathematica which is typical in FP programming.  `funcy` has flatten, `more-itertools` has flatten!
