### ISSUE TITLE
peek function

### ISSUE THREAD

**Issue by themiurgo** [pytoolz/toolz#224]
Hello,

sometimes I need to peek at the first element of an iterable. I usually implement it like this:

    def peek(iterable):
        iterator = iter(iterable)
        item = next(iterator)
        return item, itertools.chain([item], iterator)

    element, my_list = peek(my_list)

Would this be an interesting addition to toolz? If so, I'll send a pull request sometime in the future.

Cheers.

**Comment by jni** [comment]
OMG :+1:

**Comment by mrocklin** [comment]
Seems reasonable

**Comment by eriknw** [comment]
Cool.  Some questions:

1. What if the iterable is empty?  Should `peek` raise an exception, or return something that indicates that the end has been reached?
2. What if the user wants to peek at more than one element?
3. Is it worth complicating the otherwise easy-to-understand `peek` function by trying to add flexibility when addressing the above?

btw, I have reached for a `peek` function before, but I'm usually able to restructure the calculation such that I don't need it.

PR welcome.

**Comment by themiurgo** [comment]
> What if the iterable is empty? Should peek raise an exception, or return something that indicates that the end has been reached?

Good point. I'd expect a StopIteration, which is what `next(iter(iterable))` returns when `iterable` is empty.

> What if the user wants to peek at more than one element?
> Is it worth complicating the otherwise easy-to-understand peek function by trying to add flexibility when addressing the above?

A more complicated implementation addressing (2) would be something like this:

    def peek(iterable, n=0):
        iterator = iter(iterable)
        if not n:
            item = next(iterator)
            return item, itertools.chain([item], iterator)
        else:
            items = list(itertools.islice(iterator, n))
            return items, itertools.chain(items, iterator)

    # Take one element
    element, iterable = peek(iterable)

    # Take three elements
    elements, iterable = peek(iterable, 3)

    # Take one element, returned as a list
    elements, iterable = peek(iterable, 1)

I'd like to see such flexibility, but I'm not totally convinced about this solution. The returned element(s) can be either a single element or a list, which complicates the function behaviour. Also, this raises other questions on what to do when `n` is smaller than the available elements. Any thoughts?

**Comment by mrocklin** [comment]
Looks like there is some symmetry with `first:take`.  As in that situation it might be reasonable to have two separate operations.  

Personally I've only ever needed `peek` and might want to wait until someone asks for the other operation before adding it (to something other than the sandbox.)

**Comment by eriknw** [comment]
Agreed.  We can punt on peeking several elements.  Let's keep `peek` simple.  I like the proposed implementation, and I'm glad we explored additional functionality and APIs.

**Comment by themiurgo** [comment]
> Personally I've only ever needed peek and might want to wait until someone asks for the other operation before adding it (to something other than the sandbox.)

Ok, can add that to the sandbox. Which name? `peekmany`, `lookahead`?

**Comment by eriknw** [comment]
`peek` is now in (from #244).  Agreed that `peekmany`/`lookahead` should wait until it's requested for a reasonable use case.

Closing.
