### ISSUE TITLE
Additional dicttoolz functions proposal.

### ISSUE THREAD

**Issue by justanr** [pytoolz/toolz#235]
There's several things I find myself doing regularly enough I have functions that do them for me:
- Inverting a dictionary
- Inverting a dictionary with some function applied to the (old) values
- Splitting keys-values in order
- Sorting key-value pairs on some key

I'm curious if this project would be interested in adding them to the dictoolz module or the sandbox. All four are short one liners I feel make more sense with a name than just seeing them bare in the code:

``` python
def invert(d):
    return {v:k for k,v in iteritems(d)}

def invert_with(d, f):
    return {f(v):k for k,v in iteritems(d)}

def split_keys_values(d):
    return zip(*iteritems(d))

def sorted_items(d, key):
    return sorted(iteritems(d), key=key)
```

Expected behaviors:

``` python
>>> invert({'ashley': 6, 'timothy': 15})
... {6: 'ashley', 15: 'timothy'}

>>> invert_with({'ashley': [1,2,3], 'timothy': [4,5,6]}, sum)
... {6: 'ashley', 15: 'timothy'}

>>> split_keys_values({'ashley': 6, 'timothy': 15})
... (('ashley', 'timothy'), (5, 15))

>>> sorted_items({'ashley': 6, 'heather': 20, 'timothy': 15}, key=itemgetter(1))
... (('ashley', 6), ('timothy', 15), ('heather', 20))
```

Hesitantly, for itertoolz, I also propose an alias to `zip(*groups)` (or `izip` in Py2) called `unzip` only because I'm unsure how many people understand what `zip(*groups)` does.

**Comment by mrocklin** [comment]
Hrm, yes, I find myself doing the same things.  Something like these might be valuable.  The counter-argument is that, if these functions are trivial combinations of existing functions then we need to weigh the costs of adding new terms to toolz.  An alternative might be documentation that shows how to do common operations with a small set of functions.

**Comment by justanr** [comment]
True, which is why I think sandbox may be better on a provisional basis. Add them, see how often we find ourselves doing

```python
from toolz.sandbox import invert_with, split_keys_values # etc
```

rather than writing out what they're actually doing. Honestly, I usually just toss them into a lambda since they're so trivial yet so useful.

**Comment by mrocklin** [comment]
I'm generally ok with this idea.  We need to set expectations though that code in the sandbox can disappear without warning.

**Comment by justanr** [comment]
I had figured sandbox was an area for experimental/provisional code that may or may not be merged into the core modules. I'll write some tests and make a pull request in a little bit.

**Comment by eriknw** [comment]
There is also a "Tips and Tricks" section in the documentation that could use some loving.  The issues with putting stuff there is that people may not read (or remember) the documentation, the functions cannot be imported (they must be copy/pasted to be used), and the functions aren't tested.  See:

http://toolz.readthedocs.org/en/latest/tips-and-tricks.html

I also like putting tips in tricks in docstrings of existing functions.  For example, `itemmap` has an example that does the `invert` operation.  `itemmap` is also curry-able, so you can define `invert = itemmap(reversed)`.  `invert_with` could also be done with `itemmap`.

I'm not fond of `split_keys_values`.  Why not do `keys = d.keys() ; vals = d.values()`?

Also note that `sorted` is curry-able and, in fact, is in `toolz.curried`.  `sorted_items(d, key=func)` is not that shorter or more convenient than `sorted(d.items(), key=func)`.

**Comment by eriknw** [comment]
Side note: perhaps `iteritems`, `iterkeys`, and `itervalues` in `toolz.compatibility` could be aliased or renamed to `items`, `keys`, and `values` to make them more convenient to use.

**Comment by eriknw** [comment]
There is no harm in putting any or all of this in the sandbox though, so go ahead!  There is also no harm in putting them in your own repository :).  We have also discussed having an "extra miscellaneous toolz" package to put functions that are too simple or too specialized to be included in `toolz`.  We try really hard to keep the `toolz` namespace small (for many reasons), but we lose out on some perfectly reasonable functions by doing so.  The main issue with the "extra toolz" package is that neither @mrocklin or I want to take on full responsibility for it, so we need somebody else to volunteer.  Interested?

The sandbox is also intended as a space to put things until they can be broken out into their own package.  I think we need to better document the sandbox.

**Comment by justanr** [comment]
I definitely understand wanting to keep the toolz namespace as small as possible. I'll think about maintaining an `extratoolz` repo.

As for `split_keys_values`, Iunno, I just find it cleaner than doing it separately, I'm a little neurotic like that. I suppose in certain, exacting circumstances they could be desynchronized but that's more a far-flung worry than a real world one (at least on my end).

**Comment by mrocklin** [comment]
+1 on `keys`, `values`, `items`.

FWIW I like the idea of toolshed.  We could host it as part of the `pytoolz` org and point to it in the docs to give it more visibility.

**Comment by Digenis** [comment]
Regarding the inversion of dictionaries,
does the bidict module resolve your use case?
https://github.com/jab/bidict

**Comment by justanr** [comment]
@Digenis I'll have check that out more thoroughly, but it looks really interesting to say the least. My most recent use case was for attempting to create probability mappings for Markov Chains. Basically doing:

```python
>>> chain = {'cabbage': 4, 'grapes': 5, 'cheese': 1}
>>> normalize_chain(chain)
... {.4: 'cabbage', .5: 'grapes', .1: 'cheese'}
```

But I ended up finding a better way of doing it via sorting and separating the dictionary's item tuples (which also removes accidental collisions) and then doing a weight random choice.

Other than that, I find myself doing "inverted" look ups for a variety of things, usually finding lots of objects stored as values. Though, I have to admit unless I mapping back to the original dictionary or manipulating the relationship between the keys and values, `filter` is usually a better choice.

**Comment by justanr** [comment]
I'm not sure about renaming `iterkeys` et. al, `six` is a popular library that uses `iterkeys`, `itervalues`, `iteritems`. The current names keeps with this (admittedly weak) convention.
