### ISSUE TITLE
Documentation suggestion: how does pytools differ from functools, itertools etc?

### ISSUE THREAD

**Issue by endrebak** [pytoolz/toolz#238]
Just a thought. Would take some time for newcomers (like myself) to figure out.

**Comment by endrebak** [comment]
And the docs are out of date several places: groupby does now exist in itertools, despite the claims in the docs.

```
This may be because they are incomplete and lack a number of commonly related functions like compose and groupby which often complement these core operations.
```

**Comment by mrocklin** [comment]
Hi @endrebak 

PyToolz complements itertools/functools.  Yes I think you're right that it would make sense to state this more publicly somewhere.

In regards to groupby, `itertools.groupby` and `toolz.groupby` are actually very different operations.  `itertools.groupby` is somewhat of a misnomer, its functionality disagrees with the normal functionality of this name in most languages.  

Were there other locations in the docs where you found statements that appeared to be out-of-date?

**Comment by endrebak** [comment]
No, it was just that mention of groupby that existed several places in your docs.

Btw, I might want to use parts of cytoolz without requiring users of my software to download another package (half of them will be biologists that don't even know what the command line is.). Perhaps you could write something in the docs about how one should credit you guys if I just add a few of your functions to my codebase (or if you are okay with that at all).

**Comment by mrocklin** [comment]
If you want to copy and modify source then you should check out the license in the root directory of the repository.  Long story short, your code should be open source and BSD-compatibly licensed.  You would need to distribute the same cytoolz license along with your code.

If you want to copy the code without modification then you can just plop the entire directory wherever and distribute that.  It's not particularly large.

**Comment by endrebak** [comment]
Thanks.
