### ISSUE TITLE
pip is not up-to-date?

### ISSUE THREAD

**Issue by nbecker** [pytoolz/toolz#242]
I did pip install toolz (and cytoolz), then tried to import topk.  It's not there.

It looks like the pip install version is not up-to-date with the github version?

**Comment by mrocklin** [comment]
Yup.  `topk` was added recently.  It's fairly cheap to release though.  @eriknw should I go ahead and release toolz?  Anything I should wait on?

**Comment by eriknw** [comment]
Sure, we're do for a release.  `cytoolz` probably won't be ready for a matching release until this weekend, but that shouldn't stop us from releasing `toolz`.

**Comment by mrocklin** [comment]
Done.  https://pypi.python.org/pypi/toolz/0.7.2

Closing
