### ISSUE TITLE
ENH: curried operator module.

### ISSUE THREAD

**Issue by llllllllll** [pytoolz/toolz#254]
It would be very useful to have a curried operator module set. This could work by creating a dynamic submodule of `curried` that applies curried to all of the functions in `operator`.

A very common pattern is something like:

```python
map(partial(operator.add, 2), [1, 2, 3])
```

and it would be nice to say:

```python
map(toolz.curried.operator.add(2), [1, 2, 3])
```

The workaround I commonly use is:

```python
map(a.__add__, seq)
```
but that is less than ideal because it doesn't account for the `radd` of the values in the seq.

If this sounds like an appealing feature, I could work on an implementation.

**Comment by eriknw** [comment]
Funny, I was just thinking about the same thing (probably as a result of `flip`)!

**Comment by mrocklin** [comment]
I support this

**Comment by llllllllll** [comment]
My basic plan for implementation would be to just make curried a subpackage whose `__init__.py` matches the current `curried.py` and a dynamic `operator.py` that is performs a similar check to the operator module. Does that seem reasonable?

**Comment by mrocklin** [comment]
Seems reasonable to me.

Although the slowly changing and smaller nature of the operator module
might mean that it's simpler to just directly wrap every function.

**Comment by llllllllll** [comment]
merged on toolz
