### ISSUE TITLE
dissoc should be idempotent

### ISSUE THREAD

**Issue by eigenhombre** [pytoolz/toolz#258]
In my experience in Clojure, it is common to `dissoc` keys which may or may not be present on a dictionary / map, to assure they are not there.  IMO `dissoc` should be idempotent, rather than throwing KeyError when the key is not present.

E.g. `dissoc({"bar": 333}, "foo")` should not throw.  Someone coming from Clojure who uses its `dissoc` every day may find the behavior in Toolz jarring.  Happy to supply another PR if there is no objection to the proposed change.

**Comment by mrocklin** [comment]
Hrm, I could buy in to this.  This doesn't conflict with any personal use of `dissoc` that I recollect. Thoughts @eriknw ?

**Comment by eigenhombre** [comment]
Thanks all y'all.  Looks like this is complete so I shall close the issue.
