### ISSUE TITLE
release cycle question

### ISSUE THREAD

**Issue by llllllllll** [pytoolz/toolz#263]
I am just wondering how often you bundle releases. I am currently installing from git to get the curried operator changes and I was wondering when this would be on pypi. I have no issues with my current method, just curious.

**Comment by mrocklin** [comment]
Historically there hasn't been a cycle.  We've just "released" based on need.  Toolz is simple enough that releasing is pretty cheap.

I've just pushed 0.7.3 to PyPI.  Anaconda should auto-update in a day or two.
