### ISSUE TITLE
Keyword-only args breaks toolz.curry

### ISSUE THREAD

**Issue by metaperture** [pytoolz/toolz#274]
Hey guys! I would expect the following behavior from toolz.curry:

    >>> @toolz.curry
    >>> def kwonly_sum(a, *, b=10):
               return a + b
    >>> b_is_five = kwonly_sum(b=5) # actually raise exception here
    >>> b_is_five(5)
    10 # what I want

The exception gives a suggested solution:

    TypeError                                 Traceback (most recent call last)
    /home/mtartre/.conda/envs/std/lib/python3.4/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
        218         try:
    --> 219             return self._partial(*args, **kwargs)
        220         except TypeError:
    
    TypeError: kwonly_sum() missing 1 required positional argument: 'a'
    
    During handling of the above exception, another exception occurred:
    ValueError                                Traceback (most recent call last)
    <ipython-input-31-fd1daf64ecb7> in <module>()
    ----> 1 kwonly_sum(b=5)(5)
    
    /home/mtartre/.conda/envs/std/lib/python3.4/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
        220         except TypeError:
        221             # If there was a genuine TypeError
    --> 222             required_args = _num_required_args(self.func)
        223             if (required_args is not None and
        224                     len(args) + len(self.args) >= required_args):
    
    /home/mtartre/.conda/envs/std/lib/python3.4/site-packages/toolz/functoolz.py in _num_required_args(func)
        116         return known_numargs[func]
        117     try:
    --> 118         spec = inspect.getargspec(func)
        119         if spec.varargs:
        120             return None
    
    /home/mtartre/.conda/envs/std/lib/python3.4/inspect.py in getargspec(func)
        934         getfullargspec(func)
        935     if kwonlyargs or ann:
    --> 936         raise ValueError("Function has keyword-only arguments or annotations"
        937                          ", use getfullargspec() API which can support them")
        938     return ArgSpec(args, varargs, varkw, defaults)
    
    ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them

The issue is exactly the same in cytoolz. Apologies I don't have the fix in a pull request, my firm requires legal approval for that.

**Comment by metaperture** [comment]
I just noticed getfullargspec doesn't exist in py2, which makes since it doesn't have kwonly args. There will likely need to be some version switching behavior around this.

**Comment by llllllllll** [comment]
This has bit me a couple of times also. Do you have any ideas for implementing this?

**Comment by metaperture** [comment]
Adjusting the test case to cover kw-only args with no defaults provides:

    >>> @toolz.curry
    >>> def kwonly_sum(a, *, b, c=5):
    >>>     return a + b + c
    >>> kwonly_sum(10) # should raise TypeError
    >>> kwonly_sum(b=3)(2)
    10
    >>> kwonly_sum(c=3)(2) # should raise TypeError
    >>> kwonly_sum(b=5)(c=5)(5)
    15

Also, the current implementation is buggy for py2.7-like positional args as well:

    >>> @toolz.curry
    >>> def args_err(a):
    >>>     raise TypeError()
    >>> args_err(a=10) # returns curried obj, should raise

So that whole bit should probably be rewritten. I think what we really want is "do these args satisfy the call spec", so something like:


    def __call__(self, *args, **kwargs):
        try:
            return self._partial(*args, **kwargs)
        except TypeError as e:
            # available in py2.7 and py3.2+, deprecated in py3.5
            try:
                inspect.getcallargs(self._partial, *args, **kwargs)
            except TypeError:
                return curry(self._partial, *args, **kwargs)
            raise e

**Comment by metaperture** [comment]
Also, just for cleanup, I would think functoolz.py should probably have:

    if sys.version_info[0] == 2:  # pragma: no cover
        _getargspec = inspect.getargspec
    elif sys.version_info[0] == 3:
        _getargspec = inspect.getfullargspec

...at the top, then I'd think it should just call those as needed, instead of checking for sys.version_info in deeper. Maybe that's just my stylistic preference, though.

**Comment by justanr** [comment]
Might be better to place in the compatibility module and import it from there.

**Comment by metaperture** [comment]
`compatibility` sounds like a good place for `getargspec`. For the meat of the original issue here, it might be worthwhile to make a helper function to abstract out any forwards-compatibility issue and avoid the deprecated call?

    def spec_satisfied(func, args, kwargs):
        if sys.version_info[:2] < (3,5):
            bind = partial(inspect.getcallargs, func)
        else:
            bind = inspect.signature(func).bind
        try:
            bind(*args, **kwargs)
        except TypeError:
            return False
        return True

then `curry.__call__` would look pretty clean:

    def __call__(self, *args, **kwargs):
        try:
            return self._partial(*args, **kwargs)
        except TypeError as e:
            if spec_satisfied(self._partial, args, kwargs):
                raise
        return curry(self._partial, *args, **kwargs)

Or the previous one might be find if the deprecation isn't that big of an issue.

**Comment by eriknw** [comment]
Thanks for raising this issue.  I agree it's time to clean this up, especially since `inspect.getargspec` is officially deprecated in Python 3.5.

I like the idea behind `spec_satisfied`, although I would like to find a way to determine if the spec is satisfied (or unknown) without actually calling the function.

**Comment by llllllllll** [comment]
Could we use `inspect.getcallargs`, that will raise a type error if it is not satisfied but will not invoke the function?

**Comment by metaperture** [comment]
`spec_satisfied` as written above doesn't actually call the function; it just makes the arg mapping via (`inspect.Signature.bind`)[https://docs.python.org/3/library/inspect.html#inspect.Signature.bind] or via `inspect.getcallargs`.

**Comment by llllllllll** [comment]
One thing to note is that this is actually very tricky to get correct when we are thinking about 2.7 and builtin functions. We cannot inspect builtin functions with any of these tools so we still need to fall back to the current behavior.

**Comment by David-OConnor** [comment]
Is there a reason why annotations break curry, given they should be ignored by the interpreter? Type annotations work nicely with toolz's functional style, so it's a shame we can't use them on curried functions.

**Comment by mrocklin** [comment]
Annotations seem like a different issue?  @David-OConnor if you want to take a crack at solving this problem that would be quite welcome.

**Comment by David-OConnor** [comment]
Made a fork and looked through - is there a reason we can't commit one of @metaperture 's suggestions from September? They'd fix the annotation problem, the simplest of which using the version check to use getargspec or getfullargspec.

**Comment by David-OConnor** [comment]
What about:

`if sys.version_info[:2] >= (3,5):
            return len(inspect.signature(func).parameters)
        else:
            spec = inspect.getfullargspec(func)
            ...`

**Comment by eriknw** [comment]
Introspecting arg specs and checking validity is a bit of a pain to do across Python versions.  For pure Python functions, I'm inclined to use something like `mimic` posted here: https://github.com/pytoolz/toolz/issues/288#issuecomment-172742821 .  Introspecting builtin functions is being added in recent Python 3 versions, but this is not yet reliable (nor is reliability detectable--it may lie).

Supporting function annotations does seem like a different issue and would be great to have.  I have very little experience with using annotations.  Would it be sufficient to make `__annotations__` a property of `curry` that returns `self.func.__annotations__`?

**Comment by David-OConnor** [comment]
Almost ready to submit a pull: Moved num_required_args to compatibility.py; two diff versions. P2 version is unchanged. P3 version looks like this:

```
required_args = 0
        for param in inspect.signature(func).parameters.values():
            kind = param.kind
            # Presense of *args or **kwargs precludes a requirement.
            if kind in [param.VAR_POSITIONAL, param.VAR_KEYWORD]:
                return None
            # keyword only arguments, and ones with a default aren't required.
            elif kind == param.KEYWORD_ONLY or param.default != inspect._empty:
                continue
            elif kind in [param.POSITIONAL_OR_KEYWORD, param.POSITIONAL_ONLY]:
                required_args += 1
            else:
                raise AttributeError("Invalid kind found")
        return required_args
```
How do I make the unit tests work without rewriting the files? It seems like they should be methods of a TestCase class, but they're set up as standalone methods. Why's there no gitignore with likes like *~ and __pycache__ . Should I add one in the pull?

**Comment by mrocklin** [comment]
I generally run tests by running one of the following from within the toolz directory.

```
mrocklin@workstation:~/workspace/toolz$ nosetests toolz --with-doctest
......................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 214 tests in 0.102s

OK
```

or

```
mrocklin@workstation:~/workspace/toolz$ py.test toolz --doctest-modules
============================= test session starts ==============================
platform linux -- Python 3.4.4 -- py-1.4.27 -- pytest-2.7.1
rootdir: /home/mrocklin/workspace/toolz, inifile: 
collected 214 items 

toolz/dicttoolz.py .............
toolz/functoolz.py ...............
toolz/itertoolz.py .................................
toolz/recipes.py ..
toolz/curried/__init__.py .
toolz/sandbox/core.py ..
toolz/sandbox/parallel.py .
toolz/sandbox/tests/test_core.py ....
toolz/sandbox/tests/test_parallel.py .
toolz/tests/test_compatibility.py ..
toolz/tests/test_curried.py .........
toolz/tests/test_dicttoolz.py .............................................
toolz/tests/test_functoolz.py ...............................
toolz/tests/test_itertoolz.py ................................................
toolz/tests/test_recipes.py ..
toolz/tests/test_serialization.py ....
toolz/tests/test_utils.py .

========================== 214 passed in 0.74 seconds ==========================
```

**Comment by David-OConnor** [comment]
[Pull!](https://github.com/pytoolz/toolz/pull/295)

This should fix both the kwarg-only and annotation problems.

**Comment by David-OConnor** [comment]
I'm working on writing Python3-specific tests for the pull, at the request of eriknw. I have no experience with posit-only args - do y'all who do have any suggestions for test cases? The tests and expected results. Also looking for a few examples of how many required args should be returned in various cases, per a discussion with @llllllllll on the pull page.

**Comment by David-OConnor** [comment]
To start:

```
def test_curry_kwonly():
    @curry
    def f(a, *, b=10):
        return a + b

    b_is_five = f(b=5)
    assert b_is_five(3) == 15


def test_curry_annotations():
    @curry
    def f(a: int, b: float, c: str) -> Tuple[float, str]:
        return a + b, c

    assert f(5, 2.5, 'foo') == (7.5, 'foo')


def test_required_args_var_position():
    def f(a, b, *rest):
        pass

    assert num_required_args(f) == 2


def test_star_args():
    @curry
    def f(a, b, *rest):
            return (a + b), rest

    assert f(1)(2, 3, 4) == (3, (3, 4))
```

**Comment by eriknw** [comment]
#297 should solve all the issues raised here.  This discussion was extremely helpful, so thank you all.

@metaperture, here's how your examples now behave:
```python
>>> from toolz import curry
>>> 
>>> @curry
... def kwonly_sum(a, *, b=10):
...     return a + b
... 
>>> b_is_five = kwonly_sum(b=5)  # used to raise exception here
>>> b_is_five(5)
10
>>> 
>>> @curry
... def kwonly_sum(a, *, b, c=5):
...     return a + b + c
... 
>>> kwonly_sum(10) # should return curried fn
<function kwonly_sum at 0x7f3ee5238f28>
>>> kwonly_sum(b=3)(2)
10
>>> kwonly_sum(c=3)(2) # should return curried fn
<function kwonly_sum at 0x7f3ee5238f28>
>>> kwonly_sum(b=5)(c=5)(5)
15
>>> 
>>> @curry
... def args_err(a):
...     raise TypeError()
... 
>>> args_err(a=10) # should raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erik/git/toolz/toolz/functoolz.py", line 191, in __call__
    return self._partial(*args, **kwargs)
  File "<stdin>", line 3, in args_err
TypeError
>>> 
```
@David-OConnor, your tests also pass:
```python
>>> from toolz import curry
>>> from typing import Tuple
>>> 
>>> @curry
... def f(a, *, b=10):
...     return a + b
... 
>>> b_is_five = f(b=5)
>>> assert b_is_five(3) == 8
>>> 
>>> @curry
... def f(a: int, b: float, c: str) -> Tuple[float, str]:
...     return a + b, c
... 
>>> assert f(5, 2.5, 'foo') == (7.5, 'foo')
>>> 
>>> @curry
... def f(a, b, *rest):
...     return (a + b), rest
... 
>>> assert f(1)(2, 3, 4) == (3, (3, 4))
```
@metaperture and @llllllllll, thanks for suggesting `inspect.Signature.bind` for Python 3 and `inspect.getcallargs` for Python 2.  This set me on the right track.  `sig.bind` and `sig.bind_partial` are exactly what we want.  `inspect.getcallargs` had a shortcoming in that the function passed to it couldn't have `func=` as a keyword, so I had to redo the logic myself for Python 2.

`curry` should now behave much better; if it doesn't, please be vocal!

Closing once #297 is merged.

**Comment by eriknw** [comment]
Resolved.
