### ISSUE TITLE
master branch isn't reflected in PyPI release

### ISSUE THREAD

**Issue by puhrez** [pytoolz/toolz#289]
Despite the fact that the __version__ on the master branch is `0.7.4` as is the on in PyPI, there are changes found on the master branch which aren't reflected in installed versions.

For example:
`toolz.dicttoolz.dissoc` (on master)
https://github.com/pytoolz/toolz/blob/master/toolz/dicttoolz.py#L217
```
for key in keys:
        if key in d2:
            del d2[key]
```
this and its complementary doc change were committed on 2015-08-19

`toolz.dicttoolz.dissoc`  (0.7.4 per PyPI upload on 2015-08-10)
#L214

```
    for key in keys:
        del d2[key]
```

**Comment by gjcoombes** [comment]
I was wondering if `toolz.dicttoolz.assoc_in` might be included in the PyPi version too.

**Comment by eriknw** [comment]
Version 0.8.0 was just released to PyPI.
