### ISSUE TITLE
Footnote not looking so good

### ISSUE THREAD

**Issue by 3noch** [pytoolz/toolz#294]
![screen shot 2016-03-04 at 3 33 04 pm](https://cloud.githubusercontent.com/assets/882455/13539529/fade264a-e21e-11e5-98a0-186969c7b38d.png)

I'm not sure what limitations readthedocs imposes, but apparently this is one of them. Any recommended alternatives?

**Comment by eriknw** [comment]
Now that is attention to detail!  That particular footnote can be fixed to be like the others by adding a space between "change" and "[*]_" (I don't know why that fix works).  The bigger question is why the footnote markers aren't superscripted in the text.

Curiously, footnotes and their markers render properly for the sphinx documentation on readthedocs:
http://rest-sphinx-memo.readthedocs.org/en/latest/ReST.html#footnotes-ref
