### ISSUE TITLE
Would like to add `random-sample`

### ISSUE THREAD

**Issue by steven-cutting** [pytoolz/toolz#299]
I would like to contribute a simple lazy random sampling method, that is (basically) identical to Clojure's `random-sample`.

Python's library `random` has a sample function but, it is not lazy.

```python
from random import random
from toolz import filter

def random_sample(prob, col):
    return filter(lambda _: random() < prob, col)
```

Code for Clojure's `random-sample`
```clojure
(defn random-sample
  "Returns items from coll with random probability of prob (0.0 -
  1.0).  Returns a transducer when no collection is provided."
  {:added "1.7"}
  ([prob]
     (filter (fn [_] (< (rand) prob))))
  ([prob coll]
     (filter (fn [_] (< (rand) prob)) coll)))
```

I'll go ahead and wright it up and submit a pull request if that's ok?
I don't have experience with cython, so I'm not sure if I will be able to write a version for cytoolz.

**Comment by mrocklin** [comment]
Sampling opens a door to a large number of useful functions.  We might want to consider whether or not we want to dive into this and, if so, whether or not it should into the toolz library or some other related library.

**Comment by llllllllll** [comment]
This function breaks the purity presented by toolz. I am -0.5 because I think it will make it harder to write reproducible code, but I could see a version that accepts a `random.Random` to use instead just calling `random()`

**Comment by mrocklin** [comment]
@llllllllll would you be +0 if it accepted a `random.Random` as an optional parameter but created its own by default?

**Comment by llllllllll** [comment]
Yeah, that is probably fine

**Comment by mrocklin** [comment]
I'm personally not overly concerned about impurity for functions that include `random` in the name.  I don't think anyone will be surprised by non-deterministic results.

**Comment by llllllllll** [comment]
I agree that people will not be confused, but I have taken to explicitly passing random states around so that I can reliably test the code that uses randomness. Otherwise people need to do things like play with the global random seed or mock out functions.

**Comment by mrocklin** [comment]
Yeah, I definitely agree that it's nice to include the ability to specify seeds.

**Comment by steven-cutting** [comment]
An optional seed would be a very nice touch. Not having one has been one of my big complaints with the Clojure version. It would make testing a lot easier.

How about something like this:

```python
from random import Random, random
from toolz import filter

def random_sample(prob, col, rf=random):
    return filter(lambda _: rf() < prob, col)

RF = Random()
RF.seed(5)

smpl = random_sample(p, c, rf=RF)
```

This way users can optionally use whatever source of random floats they want.

**Comment by mrocklin** [comment]
Some options for names

*  `prob` or maybe `frac` (used by pandas)
* `col` should probably be `seq` to match other pronouns common in toolz
*  Thoughts on checking the type of `rf` and, if it's an int, assume the user meant to provide a seed and create a `Random` object for them, e.g. `random_sample(0.5, myseq, 12345)`

**Comment by mrocklin** [comment]
I might even prefer the variable name `seed=`, though we should probably look at what other libraries, like numpy and pandas do.

**Comment by steven-cutting** [comment]
Yeah, instead of inserting type checking for special cases, asking for a seed from the get go might be the way to go. This way we only have to test if it's `None` (or in toolz `no_default`) or an int. I think this is the more common pattern, at least in pandas. (versus checking for multiple non `None` types)

If the user really does care about using a different source of randomness it will be pretty easy to just rewrite it with a different random function. So, losing `rf` in favor of `seed` isn't a big deal.

I'll investigate pandas and friends first before writing another example.

**Comment by steven-cutting** [comment]
After looking through pandas, scikit-learn and numpy. They all follow the same pattern of having an argument `random_state` that defaults to `None` and accepts an integer seed or a [`numpy.random.RandomState`](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.random.RandomState.html) object that basically allows users to specify the distribution that they want the random numbers to come from. 
Obviously, making use of numpy's `RandomState` object in `random_sample` would be a little nuts, as that would suddenly cause numpy to become a dependency, which would kind of suck.

So, this raises two questions:
1. Should the "random state" parameter be called `seed` or `random_state`?
2. Should it accept instances of  `random.Random` and other objects with identical methods.

Personally, I think we shouldn't bother with accepting anything more that just an integer seed. Because, anything else will cause random_sample to become overly complicated to the point that it should belong in a separate package dedicated to sampling.

**Comment by mrocklin** [comment]
How about the following?  It doesn't seem too overly complicated to me and seems to satisfy all of the constraints (I think?).

```python
def random_sample(prob, seq, random_state=None):
    if random_state is None or isinstance(random_state, int):
        random_state = Random(random_state)
    ...
```

**Comment by steven-cutting** [comment]
Yeah, that looks great. 
I've noticed that some of the functions in itertoolz use `toolz.utils.no_default` instead of `None`. Would using `no_default` be prefered?

**Comment by llllllllll** [comment]
`no_default` is used when `None` is a valid value and we need to differentiate between no default argument was given and `None` was given. None should be fine here

**Comment by steven-cutting** [comment]
Ok.
I'll go ahead and write it up and submit a pull request, unless there's anything else that needs to be discussed?

**Comment by mrocklin** [comment]
This works for me.
