### ISSUE TITLE
How is it different from PyDash?

### ISSUE THREAD

**Issue by vaibhavmule** [pytoolz/toolz#305]
Pydash is utility library created by @dgilland 

https://github.com/dgilland/pydash

**Comment by mrocklin** [comment]
They're similar.  For a more thorough comparison of each project I'm afraid I'm going to have to point you to the documentation:

* http://pydash.readthedocs.io/en/latest/
* http://toolz.readthedocs.org

You may also want to read up on these other similar projects 

* https://github.com/Suor/funcy
* https://github.com/kachayev/fn.py

**Comment by vaibhavmule** [comment]
Thanks for response.
