### ISSUE TITLE
release

### ISSUE THREAD

**Issue by llllllllll** [pytoolz/toolz#306]
I would like to use `toolz.excepts` in a public project, could we release a new version on pypi/conda which includes this?

**Comment by mrocklin** [comment]
@eriknw and I were just chatting about this.  I think he was planning to do a minor release it after a two week vacation.  Is this too late for you?

**Comment by llllllllll** [comment]
I just opened a pr that was using this. I could try to refactor to not use excepts or vendor it for now.

**Comment by mrocklin** [comment]
I'd be happy to push out a micro release if that'd be useful.  

@eriknw can you think of any reason not to do this?  Is master impure in any way?

**Comment by llllllllll** [comment]
That would work for me, assuming that the everything else on master is in a reasonable state to be released

**Comment by llllllllll** [comment]
Thank you for the quick response!

**Comment by llllllllll** [comment]
Actually, it looks like I will probably not be using excepts for the code I am trying to add so there is no rush to release.

**Comment by eriknw** [comment]
Aloha!  Now is a good time to release `toolz`.  I won't be able to release a matching `cytoolz` for a couple weeks though, but that shouldn't restrict is from releasing `toolz`.

**Comment by kalefranz** [comment]
I need `excepts` too!!

**Comment by eriknw** [comment]
Okay, `cytoolz` is up to date with `toolz`.  Notably, `cytoolz` now depends on `toolz` in order to share the introspection logic.

@mrocklin, shall we release `0.8.0`?  I know we have some lingering issues/PRs, but I don't think there are any that should prevent a release.

**Comment by mrocklin** [comment]
Fine with me

**Comment by eriknw** [comment]
Version `0.8.0` has been released to PyPI.
