### ISSUE TITLE
Is checks for `no_default` fail if string is pickled

### ISSUE THREAD

**Issue by jcrist** [pytoolz/toolz#309]
Opening this for discussion, as the solution may be just "don't do that". Currently, many functions take an optional keyword argument with a default of `__no__default__`. This is checked for comparison with `is`, which in general is True if the strings are equal, and is quite fast. This fails however if the default argument is serialized using pickle:

```python
In [1]: from pickle import dumps, loads

In [2]: s = '__no__default__'

In [3]: s is s
Out[3]: True

In [4]: s2 = loads(dumps(s))

In [5]: s is s2
Out[5]: False
```

This can cause problems in dask (or at least makes the graphs a bit more complicated), as we can't just transparently pass the string through as an argument. One solution might be to use `==` instead, although this incurs a minor speed penalty:

```python
In [6]: %timeit s is s
10000000 loops, best of 3: 50.2 ns per loop

In [7]: %timeit s == s
10000000 loops, best of 3: 57.5 ns per loop

In [8]: %timeit s == s2
10000000 loops, best of 3: 59 ns per loop
```

These numbers are slightly different for python 3:

```python
In [6]: %timeit s is s
10000000 loops, best of 3: 45.2 ns per loop

In [7]: %timeit s == s
10000000 loops, best of 3: 52.9 ns per loop

In [8]: %timeit s == s2
10000000 loops, best of 3: 62.2 ns per loop
```

**Comment by eriknw** [comment]
`==` sounds good to me.
