### ISSUE TITLE
toolz.itertoolz.merge_sorted ---is not right if the original list is not sorted

### ISSUE THREAD

**Issue by suoba** [pytoolz/toolz#320]
In [57]:
list(toolz.itertoolz.merge_sorted([1, 30, 15], [2, 4, 40]))
Out[57]:
[1, 2, 4, 30, 15, 40]

It should be : 
[1, 2, 4, 15, 30, 40]

**Comment by mrocklin** [comment]
Merge_sorted assumes that the inputs are sorted

**Comment by suoba** [comment]
I see .But I don't understand why.
If the output list is sorted ,why should I care the input sorted or not, because that mean's every time we have to  spend times to make sure the inputs are sorted. I propose let the computer to finish this step.
Thank you very much.

**Comment by mrocklin** [comment]
You should use the builtin `sorted` function instead.  `merge_sorted` is a special case to operate in linear time with respect to the lengths of the inputs.
