### ISSUE TITLE
Curry functions lack IDE discover-ability

### ISSUE THREAD

**Issue by MaximilianR** [pytoolz/toolz#323]
Firstly, thank you for the awesome library!

My IDE (PyCharm) can't resolve the curried functions. I think this is because of their run-time loading.

Here's a screenshot of the issue and the solution that I run. Is there a way of keeping the universal implementation of how currying is implemented, while allowing their names & signatures to be found by static code analysis tools?

![image](https://cloud.githubusercontent.com/assets/5635139/17709151/021d49a4-63b6-11e6-9bde-aee414f030fe.png)

**Comment by eriknw** [comment]
Yeah, I bet we can figure something out.  There's no reason why `toolz.curried` shouldn't be able to play nicely with PyCharm and other introspection tools.  I actually wouldn't mind currying everything manually (explicit is better than implicit, right?), and performing the run-time checks as a test.  Thanks for the suggestion, @MaximilianR.

**Comment by eriknw** [comment]
Fixed `toolz.curried`.  `toolz.curried.operator` is still auto-populated, because it would be messier to make that module play nicely with IDEs.

Thanks again for bringing this up.  I know IDE integration and spell correct is a serious quality-of-life issue for a growing number of people!
