### ISSUE TITLE
flip objects not picklable?

### ISSUE THREAD

**Issue by dwf** [pytoolz/toolz#324]
```
In [1]: from toolz import flip

In [2]: from pickle import dumps

In [3]: dumps(flip(getattr, 'name'))
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-3-5f8f1ea21ae3> in <module>()
----> 1 dumps(flip(getattr, 'name'))

PicklingError: Can't pickle <function flip at 0x7fdb01a397b8>: it's not the same object as toolz.functoolz.flip
```

**Comment by eriknw** [comment]
oh.  wow.  Thanks, @dwf.  `memoize` has the same problem.  `flip` and `memoize` have been curried.  When pickled, they both try to pickle the original, uncurried function at, e.g., `toolz.functoolz.flip`, which now points to the curried function.  This is causing the exception.

The most straightforward fix would be to not clobber the original function so it can be referenced by an import path via pickle.  We can do this in three ways:

1. define, e.g., `_flip` and `flip = curry(_flip)` in `toolz.functoolz`
2. define `flip` in a separate module and do `flip = curry(_functoolz_no_curry.flip)` in `toolz.functoolz`.
3. keep `toolz.functoolz.flip` unmodified and curry `flip` in `toolz.__init__`.

A fancier solution is to create a `__reduce__` method for `curry` that knows whether it is a module-level global or not.  If it is, as is the case for `flip`, then `__reduce__` can simply return `self.func.__name__`.

I'd like to see if we can figure out the fancy method that works reliably, and hopefully it won't be *too* fancy.

If anybody knows a better solution, I'm all ears!

**Comment by eriknw** [comment]
Fixed.
