### ISSUE TITLE
Doctests don't execute for curried functions with nose and pytest

### ISSUE THREAD

**Issue by eriknw** [pytoolz/toolz#348]
Notably, the doctests for `flip` should fail.

**Comment by llllllllll** [comment]
This is because doctest only wants to discover classes (then their methods) and functions at module scope, not instances of custom objects. To get around this in a project that uses a lot of curries I have used:

```python
@curry
def ensure_doctest(f, name=None):
    """Ensure that an object gets doctested. This is useful for instances
    of objects like curry or partial which are not discovered by default.

    Parameters
    ----------
    f : any
        The thing to doctest.
    name : str, optional
        The name to use in the doctest function mapping. If this is None,
        Then ``f.__name__`` will be used.

    Returns
    -------
    f : any
       ``f`` unchanged.
    """
    _getframe(2).f_globals.setdefault('__test__', {})[
        f.__name__ if name is None else name
    ] = f
    return f
```

We could put something like this in the constructor to `curry` to make sure that doctests are run by default.

**Comment by eriknw** [comment]
Aha, thanks for the info.  I feel funny modifying objects in outer scopes of other projects.  #352 adds a test that runs doctests on curried objects in `toolz` by creating `toolz.__test__`.

**Comment by llllllllll** [comment]
That's fair, it could be confusing if you don't know it is happening. What do you think about putting it as a recipe in the docs, like: "if you want this, here is an example decorator that will run the doctests"

**Comment by eriknw** [comment]
Adding a note to documentation somewhere sounds like a good idea.
