### ISSUE TITLE
test_curried_exceptions test failure with 0.8.2

### ISSUE THREAD

**Issue by detrout** [pytoolz/toolz#357]
I was trying to update the Debian package to 0.8.2 from 0.8.1 and had a test failure on build

```
========================================= FAILURES ==========================================
__________________________________ test_curried_exceptions __________________________________

    def test_curried_exceptions():
        # This tests a global curried object that isn't defined in toolz.functoolz
>       merge = pickle.loads(pickle.dumps(toolz.curried.exceptions.merge))
E       AttributeError: module 'toolz.curried' has no attribute 'exceptions'

toolz/tests/test_serialization.py:65: AttributeError  
=========================== 1 failed, 174 passed in 0.80 seconds ============================
```

the most straightforward solution is this (which I could turn into a pull request). Though I'm not sure what you're actually trying to test. Though something is needed because at the bottom of toolz/curried.py is ```del exceptions``` so its probably not going to be accessible

```
diff --git a/toolz/tests/test_serialization.py b/toolz/tests/test_serialization.py
index afee159..efe8758 100644
--- a/toolz/tests/test_serialization.py
+++ b/toolz/tests/test_serialization.py
@@ -62,8 +62,8 @@ def test_flip():
 
 def test_curried_exceptions():
     # This tests a global curried object that isn't defined in toolz.functoolz
-    merge = pickle.loads(pickle.dumps(toolz.curried.exceptions.merge))
-    assert merge is toolz.curried.exceptions.merge
+    merge = pickle.loads(pickle.dumps(toolz.curried.merge))
+    assert merge is toolz.curried.merge
 
 
 @toolz.curry
```

**Comment by eriknw** [comment]
What command did you use to run the tests (so we can reproduce)?  Regardless, we should make running the tests less fragile.  Thanks for the issue and the Debian package!

**Comment by eriknw** [comment]
Okay, thanks.  The tests run fine when run with `nosetests --with-doctest`, but fail when run with a bare `nosetests` or `py.test`.  Our CI tests run the doctests.  Oops.  This should get fixed.  On the plus side, the error your seeing is benign.

**Comment by detrout** [comment]
Interestingly Debian's pybuild does something a bit interesting with the test. It looks like it installs it into a subdirectory and runs it there, and whatever side effect the doctests have don't show up there

E: pybuild pybuild:276: test: plugin distutils failed with: exit code=1: cd /build/toolz-0.8.2/.pybuild/pythonX.Y_3.5/build; python3.5 -m pytest --doctest-modules
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 3.5 returned exit code 13

**Comment by eriknw** [comment]
#358 has the fix, and we add test commands to our continuous integration script to ensure that bare `py.test` and `nosetests` commands succeed.

@detrout, do you want anything from us for the Debian build?  Would you like another tagged version on github or a release to PyPI?

**Comment by eriknw** [comment]
`toolz` and `cytoolz` now ensure that bare test commands work, and version 0.9.0 was just released.  Closing.
