### ISSUE TITLE
Any way to get PyCharm autocomplete working with PRecord?

### ISSUE THREAD

**Issue by jrbrodie77** [pytoolz/toolz#364]
(sorry for using Issues as a forum, please point me to any active forum on this project if there is one)

Is there any way to wrap a PRecord so that it does argument auto-complete/suggestion in PyCharm?

I've ended up having to do some pretty clunky stuff like:

class MyPClass(PRecord):
    x = field()
    y = fiels()

def my_pclass_create(x, y):
    return MyPClass(x=x, y=y)

This gets tedious with many arguments and named/optional args.

Is there a way to add an __init__ to a class that inherits a PRecord? So that PyCharm can introspect it?

**Comment by jrbrodie77** [comment]
Sorry I put this in the wrong project. This is for Pyrsistent.

**Comment by eriknw** [comment]
No problem, good luck!
