### ISSUE TITLE
toolz.flip bug!

### ISSUE THREAD

**Issue by samegek** [pytoolz/toolz#380]
toolz.flip(print, 'hello') =>  <function flip at 0xfed45b70>， expect print 'hello'
toolz.flip(print, 'hello', 'world') => world hello, expect print 'hello world', they are have diffrent sort.
toolz.flip(print) =><function flip at 0xfed45b70>, this is okay, just for compare with above two lines.

**Comment by llllllllll** [comment]
What do you expect the outputs should be? This looks correct to me.

**Comment by samegek** [comment]
i write

**Comment by samegek** [comment]
i rewrite content

**Comment by mikebohdan** [comment]
It's not a bug. You should look at docs.
First of all `flip` is **curried** function this means that you need to pass it all 3 arguments for execution, if you pass less arguments than it expected it should return a new function that expects rest of arguments. Let's look at example:
```python
@curry
def foo(a, b, c):
    return a + b + c

>>> a = foo(1)    # should return new function like:    lambda b, c: foo(1, b, c)
>>> b = a(2)      # should return new function like:    lambda c: a(2, c)
>>> b(3)          # executes like this:  foo(1)(2)(3)
6
```
Second one. In docs written next:`Call the function call with the arguments flipped`. This means
```python
flip(print, 'hello', 'world')
# same to
print('world', 'hello')
```
Why you expect 'hello world'?
