### ISSUE TITLE
Expose cache on memoize object

### ISSUE THREAD

**Issue by mrocklin** [pytoolz/toolz#383]
It is often convenient to be able to inspect, and possibly manipulate, the cache of a memoized function.  

Any thoughts on converting memoize to a class and exposing a `.cache` attribute?

```python
import toolz
@toolz.memoize
def f(x):
    return x + 1

f(1)

>>> print(f.cache)
{1: 2}
```

**Comment by eriknw** [comment]
Yes, this has come up before, and I think it's a good idea to expose `cache`, `key`, and `func` attributes. https://github.com/pytoolz/toolz/issues/231 https://github.com/pytoolz/toolz/issues/228

**Comment by mrocklin** [comment]
Ah, my apologies for the redundancy.  Closing in favor of those other issues.
