### ISSUE TITLE
An alternative to the builtin `sorted()` for itertoolz

### ISSUE THREAD

**Issue by rldotai** [pytoolz/toolz#390]
I was working with some data which I needed to sort prior to making use of it, and was annoyed that the builtin `sorted()` required a function when using a non-standard key, in contrast to the `pluck()` or even `topk()` implemented by toolz.
Implementing a custom sort function with a slightly more convenient API with the `getter()` function from the library was pretty easy, and so you might consider including something like the following in itertoolz:

```python
def sort(iterable, key=None, reverse=False):
    """ Return a sorted list from an iterable using the builtin `sorted()`.
    
    It has the same options but is more convenient because keys can be specified as
    strings or indices in addition to functions.
    
    # sort by index
    >>> sort([[1, 2], [3, 4], [0, 5]], key=[1])
    [[1, 2], [3, 4], [0, 5]]
    >>> sort([[1, 2], [3, 4], [0, 5]], key=1)
    [[1, 2], [3, 4], [0, 5]]
    
    # sort by key name
    >>> lst = [{'x': 109, 'y': 'm'}, {'x': 101, 'y': 'm'}, {'x': 101, 'y': 'o'}]
    >>> sort(lst, 'y')
    [{'x': 109, 'y': 'm'}, {'x': 101, 'y': 'm'}, {'x': 101, 'y': 'o'}]
    
    # sort by multiple criteria
    [{'x': 101, 'y': 'm'}, {'x': 109, 'y': 'm'}, {'x': 101, 'y': 'o'}]
    """
    if key is not None and not callable(key):
        key = getter(key)
    return sorted(iterable, key=key, reverse=reverse)
```

**Comment by ddebernardy** [comment]
You can do this already by explicitly calling Python's built-in `operator.itemgetter`:

```python
sorted(iterable, key=itemgetter(1))
```

There's also `attrgetter` for dictionaries.

https://docs.python.org/3/library/operator.html

**Comment by sitnarf** [comment]
I agree that sort should be in the library. The more important reason is the currified version of sort.

**Comment by eriknw** [comment]
`sorted` is already in `toolz.curried`.
