### ISSUE TITLE
improvements to "compose"

### ISSUE THREAD

**Issue by ariebovenberg** [pytoolz/toolz#397]
I make use of composed functions a lot, and have some suggestions for improvement:

## 1. `__repr__`

The absence of a descriptive `__repr__` hinders debugging:

```python
>>> compose(int, round)
<toolz.functoolz.Compose object at 0x103f86518>
```

Proposal:

```python
>>> compose(int, round)
compose(<class 'int'>, <built-in function round>)  # using callable's __repr__
# or
compose(int, round)  # using callable's __name__
```

## 2. equality

Since `Compose` is a sequence of functions, it makes sense that it would derive equality from its constituent objects (similar to `tuple` or `list`):

```python
>>> range == range  # invididual callable equality
True
>>> (range, len) == (range, len)  # tuples use equality of individual components
True
>>> compose(range, len) == compose(range, len)
False  # current situation
```

## 3. Binding to classes (as methods)

As mentioned in #344, composed functions declared in classes cannot be called as methods

```python
>>> class MyClass:
...     loud_repr = compose(str.upper, repr)
    
>>> MyClass().loud_repr()
...
TypeError: repr() takes exactly one argument (0 given)
```

### Option A: make `Compose` itself a descriptor

```python
class Compose:
    ...
    def __get__(self, obj, objtype=None):
        return self if obj is None else partial(self, obj)
```

```python
>>> class MyClass:
...     loud_repr = compose(str.upper, repr)
    
>>> MyClass().loud_repr()
'<__MAIN__.MYCLASS OBJECT AT 0X103F86A58>'
```

This makes the above example work. However, this may break existing code.

### Option B: a `method` helper

```python
>>> class MyClass:
...     loud_repr = method(compose(str.upper, repr))
    
>>> MyClass().loud_repr()
'<__MAIN__.MYCLASS OBJECT AT 0X103F86A58>'
```

The advantage here is that `method` is explicit, and can be used with other callables as well.

## 4. Signature introspection

As mentioned in #396, `compose` does not work nicely with python's introspection tools (i.e. the `inspect` module).

An example:

```python
>>> def format_result(number: float) -> str:
...     return 'result: {:.2f}'.format(number)
    
>>> def my_add(x: float, y: float) -> float:
...     return x + y

>>> composed = compose(format_result, my_add)
>>> inspect.signature(composed)
<Signature (*args, **kwargs)>
```

### Option A: set the first function as `__wrapped__`

```python
class Compose:
    ...
    __wrapped__ = property(attrgetter('first'))
```

```python
>>> inspect.signature(composed)
<Signature (x:float, y:float) -> float>
```

The biggest advantage is that this is python2 compatible, while still allowing `inspect.signature()` to work correctly in python3.
This downside is that the `return_annotation` is not set correctly on the resulting signature object.
In the given example, the `return_annotation` would be `float` (should be `str`)

### Option B: implement `__signature__()`

```python
>>> inspect.signature(composed)
<Signature (x:float, y:float) -> str>
```

The exact signature can be determined from the constituent functions:
The parameters can be taken from the first function, the `return_annotation` from the last function.
The disadvantage is that the logic is more complex (mainly because `inspect.signature()` does not work on all callables), and that that python2-compatibility is an issue.

I would be happy to make a PR if any of these improvements are approved.

**Comment by eriknw** [comment]
@ariebovenberg, I think all the desired changes to `compose` are in (thanks!).  Closing.  If anything was missed, please re-open.
