### ISSUE TITLE
Py37: accumulate raises StopIteration when input list is empty

### ISSUE THREAD

**Issue by nehaljwani** [pytoolz/toolz#409]
```
>>> from toolz.itertoolz import accumulate
>>> list(accumulate(add, []))
Traceback (most recent call last):
  File "/Users/nwani/m37/lib/python3.7/site-packages/toolz/itertoolz.py", line 59, in accumulate
    result = next(seq) if initial == no_default else initial
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: generator raised StopIteration
```

**Comment by groutr** [comment]
In Python 3.7, this line needs to be wrapped in a try/except construct.  I suspect that other itertoolz functions might have this error too.

Background: https://www.python.org/dev/peps/pep-0479/

**Comment by groutr** [comment]
This probably affect cytoolz as well.

**Comment by eriknw** [comment]
Thanks for the report!  I had forgotten this was coming up.  I'll give toolz attention and will try to get a release out within a week or two.  (I'm traveling for work this week, and generally have been ridiculously busy the past few months, so sorry for my lack of engagement).
