### ISSUE TITLE
Would it make sense to have `merge_with` only call the merging function when there are duplicated keys?

### ISSUE THREAD

**Issue by blaiseli** [pytoolz/toolz#430]
I was trying to use `merge_with` to merge dicts with failure in case keys appear in more than one dict.

Here is my attempt:

```python
>>> from toolz import merge_with
>>> d1 = {"A": 1, "B": 2}
>>> d2 = {"C": 3, "D": 4}
>>> def dont_merge(*values):
...     raise ValueError("The dictionaries are not supposed to share keys.")
... 
>>> merge_with(dont_merge, d1, d2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bli/.local/lib/python3.6/site-packages/toolz/dicttoolz.py", line 69, in merge_with
    return valmap(func, result, factory)
  File "/home/bli/.local/lib/python3.6/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "<stdin>", line 2, in dont_merge
ValueError: The dictionaries are not supposed to share keys.
```

From this error, I interpret that the merging function is applied on all values, even those that correspond to unique keys.

It seems that I can fix this as follows:

```python
def dont_merge(*values):
    try:
        ((val,),) = values
    except ValueError:
        raise ValueError("The dictionaries are not supposed to share keys.")
    return val
```

However, I'm wondering whether it would be feasible and useful to have an option to only call the merging function on the values corresponding to duplicated keys?

**Comment by groutr** [comment]
That seems like a very special case.  Could you explain your usage case a bit more?
You are correct that the function is applied to all values.  `merge_with` accumulates all the values for each key into a list and then calls `valmap` which does the function mapping.

As you discovered, checking for duplicated keys is pretty easy to do in the function.  I'd probably use an approach as follows.  Values will always be a list.
```python
def dont_merge(values):
    if len(values) > 1:
        raise ValueError("The dictionaries are not supposed to share keys.")
    return values[0]
```

**Comment by blaiseli** [comment]
My use case was just having a way to merge dicts that are not supposed to share keys, failing when this happened not to be the case. I realize that it would probably not be very simple to implement the option I was thinking of, and I don't actually need it to achieve the desired effect.
