### ISSUE TITLE
memory leak with curry

### ISSUE THREAD

**Issue by thejinx0r** [pytoolz/toolz#436]
We use dask for parallel computing, which in turn uses pytoolz and cytoolz.
We have a memory leak due to a reference not being dropped by dask. 

We wrote a tool to track down who is holding the reference to the memory.
We traced it back to the fact that when toolz inspects the signature of a function, it might return (not raise) an exception. The exception holds the frames and variables thus variables cannot be derenced until the exception is cleared. In #57, the result of inspecting a function is memoized, even if it's an exception. Thus, a memory leak is possible.

Our tool is gui based, so if you have a suggestion for where to upload images, I will be more than happy to provide the proof.

**Comment by eriknw** [comment]
Wow, nice sleuthing!  Sounds like a legit issue we should fix.  We're past due to release toolz and cytoolz, and I'll make sure to do so soon and to include a fix for this issue.
