### ISSUE TITLE
Add apply like in scheme.

### ISSUE THREAD

**Issue by akhilman** [pytoolz/toolz#438]
Realisztion could be:
```python
def apply(func, args):
    return func(*args)
```
Usage:
```python
>>> list(map(curry(apply)(lambda x, y: x + y), [[10, 1], [20, 2]]))
[11, 22]
```

**Comment by narfanar** [comment]
What does that expression enable on top of `curry(lambda x, y: ...)`?

I'd think its unique selling point would be for something like 'currying' args/keyword-args and waiting for the function to apply them, but that's just `tuple(...), dict(...)` and spread them at call site (or in a lambda).

**Comment by akhilman** [comment]
Actually it does nothing that lambda can't do, just looks different.

**Comment by eriknw** [comment]
Added `apply` in https://github.com/pytoolz/toolz/pull/411.  Thanks for the proposal @akhilman.  Users are free to define simple variations on their own.
