### ISSUE TITLE
Add function like apply in scheme but for kwargs.

### ISSUE THREAD

**Issue by akhilman** [pytoolz/toolz#439]
Realisztion could be:
```python
def applykw(func, kwargs):
    return func(**kwargs)
```
Usage:
```python
>>> list(map(curry(applykw)(lambda x, y: x + y), [{'x':10, 'y':1}, {'x':20, 'y':2}]))
[11, 22]
```

**Comment by eriknw** [comment]
Added `apply` in https://github.com/pytoolz/toolz/pull/411.  Thanks for the proposal @akhilman.  Users are free to define simple variations on their own.
