### ISSUE TITLE
`dissoc` on list

### ISSUE THREAD

**Issue by narfanar** [pytoolz/toolz#440]
## Expected behavior:
Indices are like 'keys' (except they change once removed). So:

```py
x = [1, 2, 3]
dissoc(x, i) # 0 <= i < 3
```

should work as expected.

## Actual behavior:

```py
from toolz import dissoc
x = [1, 2, 3]
dissoc(x, i) # 0 < i < 3
# works
dissoc(x, 0) # i == 0
>>> [1, 2, 3]
# doesn't work
```

Latest `toolz` on Python 3.7 on Anaconda.

There's probably a `None` check somewhere that doesn't check for `None` exactly.

**Comment by groutr** [comment]
@narfanar indexes are not like keys.
```python
d = {0:1, 1:1, 2:1}
0 in d  # True

L = [1, 2, 3]
0 in L  # False
```
The analog for `dissoc` on a list is `list.remove`

**Comment by narfanar** [comment]
Yeah, just noticed `dissoc`'s behavior with lists of other types (or different number sequences; what I tried with was so specifically suited to confusing me with the results...).

Remove isn't immediately applicable, though. Need to copy the list then repeat find+remove on the copy to get something that would work with several indices (passed to this new dissoc). That's basically what a binary mask would do with a numpy array.

`toolz.dissoc` does work with lists today, but it looks for values instead of keys. It makes sense given that sequence indices are not frozen (like in dicts), I guess.

**Comment by groutr** [comment]
Dissoc and the other tools in dicttoolz are specifically tailored for
mapping structures like dictionaries.

For things that operate on sequences, look at itertoolz (or itertools from
the standard library). For masking behavior specifically, there is
itertools.compress.
