### ISSUE TITLE
Unexpected curry behavior with varargs

### ISSUE THREAD

**Issue by wmayner** [pytoolz/toolz#446]
```python
from toolz import curry

@curry
def f(x, *args):
    return x + sum(args)
```
I would expect `f(0)` to be a function, but instead it returns `1`; the `*args` is interpreted as being provided, but empty.

If there's no fundamental limitation preventing it, I would find the expected behavior useful.

**Comment by llllllllll** [comment]
Curry basically keeps creating partials until a sufficient call is provided. `*args` can be empty in Python, so just `f(x)` is enough to satisfy that signature. Given the signature provided, the only way to see any interesting behavior out of `curry `would be to call `f()`, which would return `f` (or something equivalent to `f`). You may just want to use `functools.partial` from the standard library to bind the argument but not call the function.

**Comment by wmayner** [comment]
Thanks—simply using `functools.partial` is a good idea.
