### ISSUE TITLE
Python 3.5 compatibility bug

### ISSUE THREAD

**Issue by abd96** [pytoolz/toolz#449]
Hello everyone,

i am using the update_in method in python 3.5 and want to mention that this function changes the order of keys when updating my dictionary(what i don't really want :/ ).
This is not the case in python3.6 
I would appreciate any Help/Thoughts to this problem.

**Comment by MSeifert04** [comment]
Dictionaries in Python 3.5 and before are unordered, in 3.6 they are ordered but still "officially unordered". Starting with 3.7 they are officially ordered. So if you want to maintain order before 3.7 you need to use `collections.OrderedDict`.

**Comment by abd96** [comment]
Hey, 

i tried using OrderedDict and this didnt fix the problem as i am upgrading my dictionary more than once and every update has a different order(this is not the case in python3.6).

I think i will just upgrade to 3.7, thanks alot for your helpful answer :)

**Comment by MSeifert04** [comment]
> I think i will just upgrade to 3.7, thanks alot for your helpful answer :)

You're welcome. Also Python 3.7 is indeed worthwhile to have 👍 

However it seems odd that `OrderedDict` wouldn't fix the issue. Did you use it as input and *factory* argument?

**Comment by eriknw** [comment]
I think this has been resolved.  Thanks for answering @MSeifert04.

I would expect `OrderedDict` and use of the factory argument would give the desired behavior in Python 3.5.  Closing.
