### ISSUE TITLE
toolz version 1.0.0?

### ISSUE THREAD

**Issue by Artimi** [pytoolz/toolz#460]
Hi,

thank you for the great package! We use it happily in several projects. However, the latest release `0.10.0` broke some of our code. Specifically, in https://github.com/pytoolz/toolz/issues/397 in section 3.A there is explicitly written 

> This makes the above example work. However, this may break existing code.

And it indeed broke our code. It probably does not matter what the code was exactly. However, what matters is that we cannot rely on `toolz` versioning before it reaches `1.0.0` because until that you can, according to https://semver.org/#spec-item-4, change everything.

Isn't it already time to release version `1.0.0` and adhere to semver? Is there any plan towards version `1.0.0`?

**Comment by eriknw** [comment]
Excellent issue title, thanks for raising this (and sorry for breaking your code!).

Yes, it's probably past time for `toolz` to release 1.0 and follow semantic versioning.  `toolz` moves slowly and conservatively, and major changes as was done with `Compose` are rare.  `toolz` should be a reliable/safe/useful/easy package to depend on.

I expect the next release (which may drop 2.7 support) to be 1.0.0.

Regarding your breakage, could we make a hotfix to increase backwards compatibility?  Perhaps we could add a keyword to enable the new behavior.

**Comment by Artimi** [comment]
Thank you for the good news.

You mean something like (I'm not sure about the `bind` name)?
``python`
compose(f, g, bind = False)
```
Yes, that would work for us.

**Comment by Kodiologist** [comment]
Yeah, my impression is that this library is pretty mature by now and can safely release a 1.0.

**Comment by jrbourbeau** [comment]
Closing as 1.0 is out now
