### ISSUE TITLE
Publish wheel

### ISSUE THREAD

**Issue by filips123** [pytoolz/toolz#466]
Can you also publish universal Python wheel at releases? This should not be hard as the package is purely Python and this would just require adding additional `bdist_wheel` to `setup.py` building.

@pytoolz @mrocklin @jcrist @eriknw

**Comment by eriknw** [comment]
For sure.  This is my bad.  I'll publish wheels from here on out.  I plan to do a bugfix release in a week or two.

**Comment by filips123** [comment]
@eriknw Great! Can you also do this for cytoolz?

**Comment by bsolomon1124** [comment]
[Not seeing wheels as of mid-2020.](https://pypi.org/project/toolz/#files)

This is one of ~10% of packages on https://pythonwheels.com/ that lacks wheel support.

@filips123, are you open to a PR that makes this easier as part of the CI/CD pipeline?
