### ISSUE TITLE
Online docs are out of date

### ISSUE THREAD

**Issue by kevinheavey** [pytoolz/toolz#470]
The [online docs](https://toolz.readthedocs.io/en/latest/index.html) are for version 0.9.0 while the latest release is 0.10.0. 

For example, the [API documentation](https://toolz.readthedocs.io/en/latest/api.html) contains no reference to the `compose_left` function.

**Comment by eriknw** [comment]
@mrocklin, suggestions?

**Comment by mrocklin** [comment]
I logged into RTD and switched us from Python 2 to Python 3 and things seem to be fine now (maybe?)

I also added @eriknw to maintainers (my apologies for not doing this half-a-decade-ago)

**Comment by eriknw** [comment]
Great, 0.10.0 appears to be up.

@kevinheavey's observation stands though: `compose_left` is missing.  Fixed here: https://github.com/pytoolz/toolz/pull/494
