### ISSUE TITLE
A placeholder value for a curried function?

### ISSUE THREAD

**Issue by yuhanz** [pytoolz/toolz#475]
Given a function `f(a,b) = a-b`, a function `g(b)=1-b` can be derived by applying the first variable.
```
f = curry(lambda a,b: a-b)
g=f(1)
```
but, Is it possible  to apply the second variable to get `h(a)=a-2`? 

I am looking for the placeholder value in toolz, something similar to the `R._` value in Ramda.js.

**Comment by mrucci** [comment]
I'm not aware of placeholders, but for this specific case you could use [`flip`](https://toolz.readthedocs.io/en/latest/api.html#toolz.functoolz.flip), like:

```
f = curry(lambda a,b: a-b)
g = f(1)
h = flip(f)(2)
```

or via [`partial`]()

```
f = lambda a,b: a-b
g = partial(f, 1)
h = partial(flip(f), 2)
```

**Comment by yuhanz** [comment]
Thanks for the answer
