### ISSUE TITLE
`compose`, `compose_left` should allow you to name the composition

### ISSUE THREAD

**Issue by uriva** [pytoolz/toolz#479]
When debugging code that has use of `compose`, e.g.

`my_func = toolz.compose(stage3, stage2, stage1)`

And encountering an exception it might be hard to know where it came from, especially if `stageX` is itself a composition of elementary functions like `map`, `filter` etc'.

If we could somehow do `my_func = toolz.compose(stage1, stage2, stage3, name="do_something")`, and have exceptions return the line where the composition was done, that could be useful.

**Comment by mentalisttraceur** [comment]
Following the pattern in #472 and #463 , do you want to also close this old issue, since `gamla` [solves this](https://github.com/hyroai/gamla#gamladebug_exception) too?

**Comment by uriva** [comment]
yes ty
