### ISSUE TITLE
Should curry be deprecated?

### ISSUE THREAD

**Issue by caleb15** [pytoolz/toolz#504]
https://docs.djangoproject.com/en/3.1/releases/3.0/ says:

> django.utils.functional.curry() - Use functools.partial() or functools.partialmethod. See 5b1c389603a353625ae1603.

Can functools.partial or functools.partialmethod be used as a replacement for curry? If so it seems that curry should be deprecated as functools is part of the stdlib.

https://docs.python.org/3/library/functools.html#functools.partial
https://docs.python.org/3/library/functools.html#functools.partialmethod

**Comment by mrocklin** [comment]
No.  Partial isn't a replacement for curry.  I recommend looking at the
docs for curry and then seeing if partial can do all of those things.

**Comment by caleb15** [comment]
Alright, thanks.
