### ISSUE TITLE
replace blacklist/whitelist with exclude/include or denylist/allowlist

### ISSUE THREAD

**Issue by domoritz** [pytoolz/toolz#508]
The old terminology is being dropped [across tools and languages](https://www.zdnet.com/article/mysql-drops-master-slave-and-blacklist-whitelist-terminology/) so it would be nice to update this library as well.

**Comment by ruancomelli** [comment]
I strongly agree with this.

Since this would be a breaking change (`pick(whitelist=...)` wouldn't work anymore), it should be implemented before v1.0.0 comes out.

@domoritz have you seen other instances (aside from blacklist/whitelist) that should be replaced?
@eriknw what do you think?

**Comment by domoritz** [comment]
In the meantime, you could support both and update the docs to use the new terminology. I have not looked through the whole codebase. Google has a list of words to avoid at https://developers.google.com/style/word-list and guidelines for writing inclusive docs at . https://developers.google.com/style/inclusive-documentation

**Comment by eriknw** [comment]
I agree too.  Thanks for brining this to our attention.  blacklist/whitelist has been changed (and sorry it took so long to do so).  I'll look more closely at those documents when I have a chance.

Please let us know if anything else should be changed.
