### ISSUE TITLE
Continued Maintenance

### ISSUE THREAD

**Issue by mrocklin** [pytoolz/toolz#584]
It looks like there are a variety of PRs that are important for new versions of Python that aren't being handled today.  

@eriknw I'm guessing that you've moved on from active maintenance.  Is that correct?  If so, my plan is to grant a few employees of Coiled (the company that I currently control) rights to this repo and related assets (PyPI, etc..) so that they can keep the lights on while they work at that company (I reserve the rights to remove those rights afterwards).

I'll plan to do that end of week unless someone objects.

cc 
- Historical maintainers: @eriknw @eigenhombre 
- People who have helpfully raised issues and PRs recently: @cjwatson @opoplawski @AdamWill @dopplershift  (sorry for missing people)
- Suckers who I'll ask to maintain this: @jrbourbeau @fjetter @phofl @hendrikmakait

If anyone else has a recommended solution or trusted party please speak up.

**Comment by eriknw** [comment]
Thanks @mrocklin (and new maintainers); it would be great to get new maintainers to help keep the lights on! I am indeed stretched pretty thin these days and have barely been able to do minimal maintenance, so I support the proposal. I find `toolz` is actually a pleasure to work on: tests run in a second, CI finishes in a minute, and people are super nice, so I hope the new maintainers find it similarly pleasant. `toolz` could use some modernization. It feels like we just recently dropped Python 2.6 support :joy:

CC @groutr who may also be interested and whom I also trust.

**Comment by jrbourbeau** [comment]
Thanks @eriknw @mrocklin -- I'm happy to help out

**Comment by mrocklin** [comment]
@eriknw I don't have PyPI access to cytoolz.  Can you add me and James?

**Comment by jrbourbeau** [comment]
Closing as myself and @hendrikmakait have been given permissions in all the various places (this repo, PyPI, conda-forge)
