### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by mrocklin** [pytoolz/toolz#588]
I suggest that we bump the version number to 1.0.

**Comment by jrbourbeau** [comment]
+1 -- xref https://github.com/pytoolz/toolz/issues/460

**Comment by mrocklin** [comment]
Let's give @eriknw a couple days to weigh in, but otherwise can I ask you to make this happen @jrbourbeau ?

**Comment by jrbourbeau** [comment]
Yeah, releasing sometime next week sounds good to me

**Comment by jrbourbeau** [comment]
Okay, https://github.com/pytoolz/toolz/pull/590 is in so I'm going to start pushing out the 1.0 release in a few minutes

**Comment by jrbourbeau** [comment]
Closing as `toolz` and `cytoolz` 1.0 is out on PyPI and conda-forge (also the docs have been refreshed)

**Comment by Kodiologist** [comment]
Thanks, guys.
